Features/65200 benary decoupling
Orckestra/BetterRetail pull request #253
Opened 2022-09-02 08:38 UTC by OlyaAn

AB#65200

2022-09-16 08:07 UTC, InnaBoitsun requested changes

2022-09-16 08:07 UTC, InnaBoitsun commented on src/Orckestra.Composer.MyAccount/Repositories/CustomerAddressRepository.cs
> +            }
some code is duplicated - create some extention for this

2022-09-16 08:07 UTC, InnaBoitsun commented on src/Orckestra.Composer.OccClient/Orckestra.Composer.OccClient.csproj
> +    <FileAlignment>512</FileAlignment>
solution projects have 4.8 framework, use the same

2022-09-16 08:07 UTC, InnaBoitsun commented on src/Orckestra.Composer.OccClient/Properties/PublishProfiles/Package.pubxml
> +</Project>
is it needed?

2022-09-16 08:36 UTC, OlyaAn commented on src/Orckestra.Composer/Caching/ICacheClientV2.cs
> +    {
yes, in the CacheProvider.cs

2022-09-22 13:03 UTC, InnaBoitsun approved these changes

2022-09-22 13:07 UTC, merged