feature #65984-Variant Color Configuration Managing
Orckestra/BetterRetail pull request #297
Opened 2022-10-13 11:40 UTC by Anstsiya

2022-10-17 07:25 UTC, InnaBoitsun reviewed
I did not check yet the implementation but I see next visual issues:
1) it is not possible to close Color Picker when it is opened - clicking outside did not help
2) when filter is used it shows old colors in Picker (from prev items) 
![image](https://user-images.githubusercontent.com/6649972/196112989-7a6aab4d-0beb-4ebb-8fb0-ad216d9cf01c.png)
3) is it possible to show white instead of black when color is absent?
4) I was not able to Save - I see error in JS:
![image](https://user-images.githubusercontent.com/6649972/196113141-9988a02c-1717-4580-b22b-5e9c623c60ee.png)
5) when all colors are rendered it looks like C1 hangs on and it is not possible to switch tabs
- need to think more here to have better implementation ( some paging or  show first XXX items and "show more" btn at bottom)

2022-10-18 10:30 UTC, Anstsiya commented
resolved comments for now except 
5. when all colors are rendered it looks like C1 hangs on and it is not possible to switch tabs
need to think more here to have better implementation ( some paging or show first XXX items and "show more" btn at bottom)

2022-10-19 08:01 UTC, InnaBoitsun reviewed
Color Pciker doesn work, It does not display selected color and when click on input, the selected color is not applied

2022-10-24 11:11 UTC, neexite commented on src/Orckestra.Composer.Product/GraphQL/Extensions/DataGraphQLExtensions.cs
> +    public static class DataGraphQLExtensions
Move reusable classes to the common dll (Composer or separated library)

2022-10-27 08:05 UTC, InnaBoitsun reviewed
After the Save the new colors disapper from inputs - see creen:
![KTjD5fcF85](https://user-images.githubusercontent.com/6649972/198227471-4f0ac6c1-3837-4f21-893c-13eb02fa8d69.gif)

2022-10-27 09:59 UTC, neexite requested changes

2022-10-27 09:59 UTC, neexite commented on src/Orckestra.Composer.Product/GraphQL/Extensions/LambdaExtensions.cs
> +namespace Orckestra.Composer.Product.GraphQL.Extensions
Move reusable classes to the common dll (Composer or separated library)

2022-10-27 09:59 UTC, neexite commented on src/Orckestra.Composer.Product/GraphQL/Extensions/LambdaExtensions.cs
> +    public static class LambdaExtensions
to common dll

2022-10-27 09:59 UTC, neexite commented on src/Orckestra.Composer.Product/GraphQL/Types/DataInput.cs
> +    public class DataInput<TSourceType> where TSourceType : class, IData
to common dll

2022-10-27 09:59 UTC, neexite commented on src/Orckestra.Composer.Product/GraphQL/Types/DataInputObjectGraphType.cs
> +    public class DataInputObjectGraphType<TSourceType> : AutoRegisteringInputObjectGraphType<TSourceType> where TSourceType : class, IData
to common dll

2022-10-27 09:59 UTC, neexite commented on src/Orckestra.Composer.Product/GraphQL/Types/DataObjectGraphType.cs
> +    public class DataObjectGraphType<TSourceType> : AutoRegisteringObjectGraphType<TSourceType>
to common dll

2022-10-27 09:59 UTC, neexite commented on src/Orckestra.Composer.Product/StartupHandler.cs
> +            EnsureCreateStore();
Is it required?

2022-10-27 09:59 UTC, neexite commented on tests/Orckestra.Composer.Sitemap.Tests/app.config
> +        <bindingRedirect oldVersion="0.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
why it there?

2022-10-27 09:59 UTC, neexite commented on src/Orckestra.Composer.Product/StartupHandler.cs
> +            //GraphQL, NOTE: may be move to IRecipeDocumentExecuter and IRecipeDocumentWriter
Implement notes :-)
Think about reusing

2022-10-31 09:42 UTC, neexite approved these changes

2022-11-01 13:00 UTC, merged